python fairseq_translate.py --sampling --sampling_topk=-1
python fairseq_translate.py --sampling --sampling_topk=1
python fairseq_translate.py --sampling --sampling_topk=10
python fairseq_translate.py --sampling --sampling_topk=50
python fairseq_translate.py --sampling --sampling_topk=100
python fairseq_translate.py --sampling --sampling_topp=0.5
python fairseq_translate.py --sampling --sampling_topp=0.8
python fairseq_translate.py --sampling --sampling_topp=0.9
python fairseq_translate.py --beam=5
python fairseq_translate.py --beam=10